# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\课程作业资料\自动化专业综合实践\code\myqt\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 710)
        self.oldPic = QtWidgets.QLabel(Form)
        self.oldPic.setGeometry(QtCore.QRect(110, 120, 320, 240))
        self.oldPic.setScaledContents(True)
        self.oldPic.setAlignment(QtCore.Qt.AlignCenter)
        self.oldPic.setObjectName("oldPic")
        self.newPic = QtWidgets.QLabel(Form)
        self.newPic.setGeometry(QtCore.QRect(570, 120, 320, 240))
        self.newPic.setScaledContents(True)
        self.newPic.setAlignment(QtCore.Qt.AlignCenter)
        self.newPic.setObjectName("newPic")
        self.upload = QtWidgets.QPushButton(Form)
        self.upload.setGeometry(QtCore.QRect(400, 460, 93, 28))
        self.upload.setObjectName("upload")
        self.transform = QtWidgets.QPushButton(Form)
        self.transform.setGeometry(QtCore.QRect(540, 460, 93, 28))
        self.transform.setObjectName("transform")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(540, 530, 93, 28))
        self.save.setObjectName("save")
        self.style = QtWidgets.QToolButton(Form)
        self.style.setGeometry(QtCore.QRect(400, 530, 93, 28))
        self.style.setObjectName("style")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.oldPic.setText(_translate("Form", "原图"))
        self.newPic.setText(_translate("Form", "转换后图片"))
        self.upload.setText(_translate("Form", "上传图片"))
        self.transform.setText(_translate("Form", "开始转换"))
        self.save.setText(_translate("Form", "保存结果"))
        self.style.setText(_translate("Form", "风格选择"))
